### ISSUE TITLE
Zu kopierende Dateien in der config definieren

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/redaxo-mit-bimmelbam#1]
dazu müsste der Copy Task angepasst werden.

**Comment by schuer** [comment]
Du hast recht, der Copy-Task ist nicht generisch aufgebaut, im Gegensatz zu eigentlich allen anderen Tasks. Das liegt daran, dass Bimmelbam aus anderen Projekten zusammenkopiert wurde, und dort brauchten wir spezifischere Copy-Tasks, so dass die zentrale Config nicht sinnvoll schien.

Vielleicht sollten wir hier auch in Richtung Best Practice handeln und die Copy-Informationen in die Config stecken, um den Task generisch zu halten.

**Comment by schuer** [comment]
Ich assigne mal von mir weg. Vielleicht will das ja jemand von den Mitlesenden umsetzen.
Ich habe aktuell noch ein paar andere Baustellen.
