### ISSUE TITLE
gulp to webpack?

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/redaxo-mit-bimmelbam#10]

**Comment by schuer** [comment]
Ich persönlich habe aktuell keine Absicht, das Setup zu ändern. Es funktioniert prima so, wie es ist. Gulp wird schon seit einiger Zeit nicht mehr wirklich weiterentwickelt, so dass es potentiell in Gefahr läuft, nicht mehr das richtige Tool zu sein. Aber sollten wir das Setup hier anpassen wollen, etwa in Richtung Webpack, würde das sicherlich ein neues Projekt werden. Bimmelbam 2 quasi.

**Comment by schuer** [comment]
Bei Bedarf gerne nochmal öffnen.
