### ISSUE TITLE
The 'templates' task in gulp.watch() incorrectly logs as <anonymous>

### ISSUE THREAD

**Issue by nandes2062** [FriendsOfREDAXO/redaxo-mit-bimmelbam#19]
The bug occurs after it is updated to Gulp 4

**Comment by gharlan** [comment]
Hmm, it works for me:

![screenshot 2018-05-12 13 26 42](https://user-images.githubusercontent.com/330436/39956829-3db6481e-55e8-11e8-9643-a183477828cc.png)

**Comment by gharlan** [comment]
Oh I'm sorry, your are talking about gulp.watch(). I can confirm this:

![screenshot 2018-05-12 13 36 03](https://user-images.githubusercontent.com/330436/39956888-756ce0f0-55e9-11e8-9712-4f9124782f29.png)

**Comment by nandes2062** [comment]
If I'm talking about gulp.watch (), and if they are resolved with #21

**Comment by schuer** [comment]
Fixed, thx @gharlan for the fix and @nandes2062 for mentioning!
