### ISSUE TITLE
browserslist in package.json?

### ISSUE THREAD

**Issue by gharlan** [FriendsOfREDAXO/redaxo-mit-bimmelbam#2]
https://github.com/postcss/autoprefixer#browsers

Dort habe ich gelesen, dass es besser wäre, die browserlist als separate Datei oder in der package.json zu hinterlegen, da dann auch andere Tools die Liste berücksichtigen.

Aktuell wird es ja als Config direkt an autoprefixer weitergegeben.

@schuer Was meinst du dazu?

**Comment by schuer** [comment]
Sicherlich sehr sinnvoll, ja. Wenn wir dieses Bimmelbam-Projekt konsequent in Richtung »best practice« ausbauen wollen, sollten wir es mit aufnehmen. Wenn es aber sowieso nur für den schnellen Einstieg ist — das war meine eigentliche Motivation, deshalb fehlt auch das ganze Linting, Testing, Deployment und Bla —, dann könnten wir es auch so lassen, wie es ist.

Im Zweifel Best Practice, oder? :)

**Comment by gharlan** [comment]
Ich finde das Repo ganz praktisch, um anhand dessen immer mal wieder über (neue) Best Practices sich auszutauschen etc.

Ansonsten würde ich einfach abwarten, was denn so kommt an Issues/PRs, und dann schauen, wie oder zu was sich dieses Repo entwickelt.
Für dieses Issue werde ich wohl einen PR erstellen.

**Comment by schuer** [comment]
Habe eine `.browserslistrc` statt der `package.json` verwendet, einfach aus dem Grund, der einem bei solchen Dingen so oft negativ aufstößt: In einem JSON-File kann/darf man nicht kommentieren.
