### ISSUE TITLE
Error trying to import via ES6-modules from node_modules

### ISSUE THREAD

**Issue by nandes2062** [FriendsOfREDAXO/redaxo-mit-bimmelbam#22]
in source/scripts/script.js: When trying to import via 'ES6-modules' from node_modules the following error occurs...
![es6modules](https://user-images.githubusercontent.com/6126258/42293446-4376cf6e-7fa8-11e8-8e1f-326aa0366829.jpg)

**Comment by schuer** [comment]
Thx @nandes2062, I will take care of the issue soon!

**Comment by schuer** [comment]
Sorry it took me so long, @nandes2062. Should be all working now.

* [Bootstrap 4.1.3 finally provides UMD modules](https://github.com/twbs/bootstrap/releases/tag/v4.1.3) to import separately in any contexts. Bimmelbam is now able to use the carousel without including the whole bootstrap JS.
* Babel 7 handles all the stuff 🎉

**Comment by schuer** [comment]
ES6 vs CommonJS/node modules looks like this:

![bildschirmfoto 2018-10-03 um 23 42 32](https://user-images.githubusercontent.com/1297466/46441196-13592100-c766-11e8-84f7-5721be7962f0.png)
