### ISSUE TITLE
gulp-cssnano ist deprecated

### ISSUE THREAD

**Issue by gharlan** [FriendsOfREDAXO/redaxo-mit-bimmelbam#30]
gulp-cssnano wird nicht weiterentwickelt: https://github.com/ben-eb/gulp-cssnano

Daher ist ein Update auf cssnano 4 nicht möglich, da gulp-cssnano noch cssnano 3.x verwendet.

Lösung: cssnano als Plugin für postcss verwenden.
In unseren yakamara/gulp-tasks habe ich es so gelöst: https://github.com/yakamara/gulp-tasks/commit/46dddad5fea76e4edd5b02a476ded4915672c9b5

**Comment by schuer** [comment]
Done. Danke @gharlan!
