### ISSUE TITLE
'libpng12-dev' has no installation candidate

### ISSUE THREAD

**Issue by PeterTheOne** [FriendsOfREDAXO/redaxo-mit-bimmelbam#31]
I got an error `E: Package 'libpng12-dev' has no installation candidate` when running `docker-compose up -d`.

Changing `libpng12-dev` to `libpng-dev` helped, see https://askubuntu.com/a/991711/424983

**Comment by schuer** [comment]
Fixed. Thanks @PeterTheOne!
