### ISSUE TITLE
Change from uglify to terser

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/redaxo-mit-bimmelbam#38]
> Why choose terser?
> 
> uglify-es is no longer maintained and uglify-js does not support ES6+.
> terser is a fork of uglify-es that mostly retains API and CLI compatibility with uglify-es and uglify-js@3.

https://github.com/terser/terser

**Comment by gharlan** [comment]
Den Schritt bin ich bei uns auch gegangen: https://github.com/yakamara/gulp-tasks/commit/690c981e49c34c59e3bf35be0f32ea7be730d3bd
(gulp-uglify-es scheint ein gulp wrapper für terser zu sein, verwendet also nicht mehr uglify-es).
