### ISSUE TITLE
Feature: Google Fonts einbinden

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/redaxo-mit-bimmelbam#4]
Anregung von @joachimdoerr, dass ein Beispiel für die Einbindung von Google Fonts nett wäre.

**Comment by tbaddade** [comment]
Ich schiebe die Fonts immer auf den Server. Kleiner Helfer für Googlefonts wäre das hier:
https://google-webfonts-helper.herokuapp.com/fonts

**Comment by schuer** [comment]
Danke für die Anregung, @tbaddade.
In diesem Fall finde ich es einfacher, direkt von Google zu laden. Damit ist es quasi ein Zweizeiler, während für die lokale Verwendung auch der Gulp-Copy-Task erweitert werden müsste, ein Sass-Font-Partial angelegt werden sollte und vermutlich einige Kommentare zur Hilfe ergänzt werden müssten.
