### ISSUE TITLE
bimmelbam mit docker

### ISSUE THREAD

**Issue by joachimdoerr** [FriendsOfREDAXO/redaxo-mit-bimmelbam#5]
Das fänd ich persönlich ja eine spitzenmäßige Kombination!

**Comment by schuer** [comment]
In welcher Form hättest du es denn gerne: 1. Das ganze Node-Bimmelbam läuft im Container, oder 2. Der Container stellt nur den LAMP-Stack bereit, und das Node-Bimmelbam läuft außerhalb auf dem Client?

Viele nutzen Variante 1, wir haben im Team allerdings mal beschlossen, Variante 2 zu verwenden, weil es merklich performanter ist. Es erfordert allerdings, dass alle Beteiligten das Setup auf ihren Clients durchlaufen.

Falls du Variante 2 möchtest: Die ist wirklich ganz schnell implementiert und erfordert nur ein paar Docker-Konfigurationsdateien. Variante 1 wäre aufwendiger, und da habe ich leider auch wenig Lust drauf. Dafür müssten wir dann jemanden suchen bei FOR.

**Comment by elricco** [comment]
Also ich hab es gemacht am Wochenende für meine Zwecke in Variante 2. Läuft gut und der Austausch innerhalb meiner Arbeitsplätze war schnell und reibungslos.

**Comment by schuer** [comment]
@elricco Top! Willst du es vielleicht als PR reingeben?

**Comment by joachimdoerr** [comment]
@elricco super! PR wäre doch genial, dann kann @schuer das checken und überlegen ob es zu bimmelbam passt.

**Comment by elricco** [comment]
@joachimdoerr Ich schaue mal, was ob ich das am Wochenende hinbekommen - ich wollte die Struktur eh nochmal überdenken 😄

**Comment by schuer** [comment]
Weil mein MAMP auf beiden Kisten regelmäßig hängt und quasi nicht mehr benutzbar ist, habe ich jetzt doch mal Docker ins Bimmelbam gebracht, um den Apache und MySQL bereitzustellen. Ich hoffe, das macht Bimmelbam nicht unnötig komplex. Habe in der README versucht, klar zu beschreiben, dass Docker am Ende nur optional ist, und dass man die 4 zugehörigen Ordner und Dateien andernfalls bedenkenlos aus dem Projekt löschen kann.

**Comment by nandes2062** [comment]
Ich habe meinen eigenen Bimmelban, gemach und bin bereit mit Vanilla Js, Pug und Edgrid Templates (Sass) zu arbeiten, was einen Style Guide in der Demo beinhaltet.
PS: Entferne Bootstrap, entferne Jquery und entferne die Nunjucks.
https://gitlab.com/2062nandes/redaxo-mit-bimmelbam-2

**Comment by schuer** [comment]
Nice, @nandes2062! Why did you choose Pug (Jade) over Nunjucks? Technical reasons or just used to working with it?

And of course you’re right, we don’t require Bootstrap and jQuery. It’s just for demo purposes.

_(Also, should I write in English or in German?)_

**Comment by nandes2062** [comment]
I choose pug for the required indentation and the simplicity of writing code, and another reason is that my style guide is written in pug
